//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANSAR2013.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SANSAR2013.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Actions_office_chart_pie {
            get {
                object obj = ResourceManager.GetObject("Actions-office-chart-pie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arama {
            get {
                object obj = ResourceManager.GetObject("arama", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arizali_giris_16x16 {
            get {
                object obj = ResourceManager.GetObject("arizali_giris_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arizali_giris_16x161 {
            get {
                object obj = ResourceManager.GetObject("arizali_giris_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap defolu_stok {
            get {
                object obj = ResourceManager.GetObject("defolu_stok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap diger_kullanici_islemleri {
            get {
                object obj = ResourceManager.GetObject("diger_kullanici_islemleri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duzenle {
            get {
                object obj = ResourceManager.GetObject("duzenle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ekle {
            get {
                object obj = ResourceManager.GetObject("ekle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap excell {
            get {
                object obj = ResourceManager.GetObject("excell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatura_no {
            get {
                object obj = ResourceManager.GetObject("fatura_no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fis_no {
            get {
                object obj = ResourceManager.GetObject("fis_no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap giris {
            get {
                object obj = ResourceManager.GetObject("giris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap giris_1 {
            get {
                object obj = ResourceManager.GetObject("giris_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap giris_2 {
            get {
                object obj = ResourceManager.GetObject("giris_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap giris_3 {
            get {
                object obj = ResourceManager.GetObject("giris_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap giris_31 {
            get {
                object obj = ResourceManager.GetObject("giris_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap giris_4 {
            get {
                object obj = ResourceManager.GetObject("giris_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap giris1 {
            get {
                object obj = ResourceManager.GetObject("giris1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gonder {
            get {
                object obj = ResourceManager.GetObject("gonder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guncelle {
            get {
                object obj = ResourceManager.GetObject("guncelle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guncelle1 {
            get {
                object obj = ResourceManager.GetObject("guncelle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hakkinda {
            get {
                object obj = ResourceManager.GetObject("hakkinda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap html {
            get {
                object obj = ResourceManager.GetObject("html", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icerik_full {
            get {
                object obj = ResourceManager.GetObject("icerik_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icerik_gor {
            get {
                object obj = ResourceManager.GetObject("icerik_gor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Illustrator1 {
            get {
                object obj = ResourceManager.GetObject("Illustrator1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap irsaliye_no {
            get {
                object obj = ResourceManager.GetObject("irsaliye_no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kapat {
            get {
                object obj = ResourceManager.GetObject("kapat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kaydet {
            get {
                object obj = ResourceManager.GetObject("kaydet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap konsinye_siparis_hareket {
            get {
                object obj = ResourceManager.GetObject("konsinye_siparis_hareket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kullanici_ekle {
            get {
                object obj = ResourceManager.GetObject("kullanici_ekle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kullanici_listesi {
            get {
                object obj = ResourceManager.GetObject("kullanici_listesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kullanicilar {
            get {
                object obj = ResourceManager.GetObject("kullanicilar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lens {
            get {
                object obj = ResourceManager.GetObject("lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap masa_ustu {
            get {
                object obj = ResourceManager.GetObject("masa_ustu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap musteri_islem {
            get {
                object obj = ResourceManager.GetObject("musteri_islem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap musteri_karti {
            get {
                object obj = ResourceManager.GetObject("musteri_karti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap musteri_listesi {
            get {
                object obj = ResourceManager.GetObject("musteri_listesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap musteriler {
            get {
                object obj = ResourceManager.GetObject("musteriler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pc {
            get {
                object obj = ResourceManager.GetObject("pc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pdf {
            get {
                object obj = ResourceManager.GetObject("pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap raporlar {
            get {
                object obj = ResourceManager.GetObject("raporlar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resim_ekle {
            get {
                object obj = ResourceManager.GetObject("resim_ekle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satis_iade {
            get {
                object obj = ResourceManager.GetObject("satis_iade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satis_iade_16x16 {
            get {
                object obj = ResourceManager.GetObject("satis_iade_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satis_iade_listesi {
            get {
                object obj = ResourceManager.GetObject("satis_iade_listesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satis_iade1 {
            get {
                object obj = ResourceManager.GetObject("satis_iade1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satis_listesi {
            get {
                object obj = ResourceManager.GetObject("satis_listesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satis_onay {
            get {
                object obj = ResourceManager.GetObject("satis_onay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sec {
            get {
                object obj = ResourceManager.GetObject("sec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sec_up {
            get {
                object obj = ResourceManager.GetObject("sec_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap secim_tmm {
            get {
                object obj = ResourceManager.GetObject("secim_tmm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap serv_cikis {
            get {
                object obj = ResourceManager.GetObject("serv_cikis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server {
            get {
                object obj = ResourceManager.GetObject("server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap servis {
            get {
                object obj = ResourceManager.GetObject("servis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap servis_stok {
            get {
                object obj = ResourceManager.GetObject("servis_stok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sil {
            get {
                object obj = ResourceManager.GetObject("sil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sil1 {
            get {
                object obj = ResourceManager.GetObject("sil1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap siparis {
            get {
                object obj = ResourceManager.GetObject("siparis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap siparis_16x16 {
            get {
                object obj = ResourceManager.GetObject("siparis_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap siparis_hareket {
            get {
                object obj = ResourceManager.GetObject("siparis_hareket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap siparis_islemleri {
            get {
                object obj = ResourceManager.GetObject("siparis_islemleri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap siparis_listesi {
            get {
                object obj = ResourceManager.GetObject("siparis_listesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap siparis_listesi1 {
            get {
                object obj = ResourceManager.GetObject("siparis_listesi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap start_menu {
            get {
                object obj = ResourceManager.GetObject("start_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stok_giris_16x16 {
            get {
                object obj = ResourceManager.GetObject("stok_giris_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stok_karti {
            get {
                object obj = ResourceManager.GetObject("stok_karti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stok_kayit {
            get {
                object obj = ResourceManager.GetObject("stok_kayit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stok_listesi {
            get {
                object obj = ResourceManager.GetObject("stok_listesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stok_onay {
            get {
                object obj = ResourceManager.GetObject("stok_onay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stok_tanitim {
            get {
                object obj = ResourceManager.GetObject("stok_tanitim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tumunu_goster {
            get {
                object obj = ResourceManager.GetObject("tumunu_goster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user96x96 {
            get {
                object obj = ResourceManager.GetObject("user96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yazdir {
            get {
                object obj = ResourceManager.GetObject("yazdir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yeni {
            get {
                object obj = ResourceManager.GetObject("yeni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yeni_gir {
            get {
                object obj = ResourceManager.GetObject("yeni_gir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yenile {
            get {
                object obj = ResourceManager.GetObject("yenile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yenile_1 {
            get {
                object obj = ResourceManager.GetObject("yenile_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
